# Generated by Django 6.0.2 on 2026-04-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tnrs', '0002_order_quantity_order_total_price_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
